### ISSUE TITLE
IF NOT EXIST should not be used in an extension script

### ISSUE THREAD

**Issue by gleu** [dalibo/pg_query_settings#23]
I'd rather have an error if the table already exists. Otherwise, we might end up with a table that doesn't have our table's definition, and it will make our extension fail badly. It would be better to fail early, when the extension is created.

**Comment by tilkow** [comment]
Fixed in [11a3a00 ](https://github.com/dalibo/pg_query_settings/commit/11a3a00eeeb616f938ca40758a38551d922269bf).
