### ISSUE TITLE
Examples in the README files don't use the standard psql prompt

### ISSUE THREAD

**Issue by gleu** [dalibo/pg_query_settings#3]
They use my .psqlrc config. We should probably use the standard config.

Moreover, we see WARNINGs. By default, we shouldn't see them. And the code has been changed: they aren't WARNING anymore (DEBUG level right now).

**Comment by yhuelf** [comment]
fixed in f2dcdf24

**Comment by tilkow** [comment]
fix last part of this issue with PR #10 .
